/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CmdkPlaceholder: typeof import('./src/components/common/CmdkPlaceholder.vue')['default']
    FigmaIcon: typeof import('./src/components/icons/FigmaIcon.vue')['default']
    Home: typeof import('./src/components/command/raycast/Home.vue')['default']
    Item: typeof import('./src/components/command/raycast/Item.vue')['default']
    Linear: typeof import('./src/components/command/Linear.vue')['default']
    LinearAssignToIcon: typeof import('./src/components/icons/LinearAssignToIcon.vue')['default']
    LinearAssignToMeIcon: typeof import('./src/components/icons/LinearAssignToMeIcon.vue')['default']
    LinearChangeLabelsIcon: typeof import('./src/components/icons/LinearChangeLabelsIcon.vue')['default']
    LinearChangePriorityIcon: typeof import('./src/components/icons/LinearChangePriorityIcon.vue')['default']
    LinearChangeStatusIcon: typeof import('./src/components/icons/LinearChangeStatusIcon.vue')['default']
    LinearIcon: typeof import('./src/components/icons/LinearIcon.vue')['default']
    LinearRemoveLabelIcon: typeof import('./src/components/icons/LinearRemoveLabelIcon.vue')['default']
    LinearSetDueDateIcon: typeof import('./src/components/icons/LinearSetDueDateIcon.vue')['default']
    Logo: typeof import('./src/components/icons/Logo.vue')['default']
    MoonIcon: typeof import('./src/components/icons/MoonIcon.vue')['default']
    Projects: typeof import('./src/components/command/vercel/Projects.vue')['default']
    Raycast: typeof import('./src/components/command/raycast/Raycast.vue')['default']
    RaycastClipboardIcon: typeof import('./src/components/icons/RaycastClipboardIcon.vue')['default']
    RaycastDarkIcon: typeof import('./src/components/icons/RaycastDarkIcon.vue')['default']
    RaycasTerminalIcon: typeof import('./src/components/icons/RaycasTerminalIcon.vue')['default']
    RaycastFinderIcon: typeof import('./src/components/icons/RaycastFinderIcon.vue')['default']
    RaycastHammerIcon: typeof import('./src/components/icons/RaycastHammerIcon.vue')['default']
    RaycastIcon: typeof import('./src/components/icons/RaycastIcon.vue')['default']
    RaycastLightIcon: typeof import('./src/components/icons/RaycastLightIcon.vue')['default']
    RaycastStarIcon: typeof import('./src/components/icons/RaycastStarIcon.vue')['default']
    RaycastWindowIcon: typeof import('./src/components/icons/RaycastWindowIcon.vue')['default']
    Self: typeof import('./src/components/command/Self.vue')['default']
    SlackIcon: typeof import('./src/components/icons/SlackIcon.vue')['default']
    SunIcon: typeof import('./src/components/icons/SunIcon.vue')['default']
    Vercel: typeof import('./src/components/command/vercel/Vercel.vue')['default']
    VercelContactIcon: typeof import('./src/components/icons/VercelContactIcon.vue')['default']
    VercelCopyIcon: typeof import('./src/components/icons/VercelCopyIcon.vue')['default']
    VercelDocsIcon: typeof import('./src/components/icons/VercelDocsIcon.vue')['default']
    VercelFeedbackIcon: typeof import('./src/components/icons/VercelFeedbackIcon.vue')['default']
    VercelIcon: typeof import('./src/components/icons/VercelIcon.vue')['default']
    VercelPlusIcon: typeof import('./src/components/icons/VercelPlusIcon.vue')['default']
    VercelProjectsIcon: typeof import('./src/components/icons/VercelProjectsIcon.vue')['default']
    VercelTeamsIcon: typeof import('./src/components/icons/VercelTeamsIcon.vue')['default']
    YouTubeIcon: typeof import('./src/components/icons/YouTubeIcon.vue')['default']
  }
}
